### PR TITLE
github issue #8, added deep immutability, updateIn

### PR DESCRIPTION
**Pull request by NickStefan**
added deeper immutability by using immutable.js fromJS() method when
setting the initial irecord (this will transform deeper arrays and objects when setting the irecord).

exposed the updateIn immutable method to irecord. this takes a transform
method and makes dealing with updating arrays (and their keys) easier.

added two tests.

### CODE REVIEW

**Comment by troutowicz** [comment]
:+1:

**Comment by ericelliott** [comment]
I'm not a big fan of the immutable API and wanted to keep it more simple but now I'm waffling.

Now I'm hungry for waffles.

waffles

**Comment by ericelliott** [comment]
Please use `$ npm run check` and get all the preflight checks passing. =)

**Comment by NickStefan** [comment]
I understand what you mean about keeping it simple, but using set without a transform function makes it tough to manage an array. the transform methods _could_ be mapped to a method of the wrapper class though: 

```
rec.set( 'keyThatGetsAnArray' ).push("new value")
rec.set( 'keyThatGetsAnArray' ).splice( ... args ...)
// etc
```

but exposing the inner transform API was the simpler solution I took here.

btw, love the package set up. the testing, linting, building, and prechecking are all real nice.

**Comment by ericelliott** [comment]
@NickStefan Would you mind opening a new issue for the `.updateIn()` functionality? That's really an entirely separate issue, and we need to think a little more carefully about the API.

Please review #10.

**Pull request closed without merging**
